# Generated by Django 6.0.4 on 2026-05-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.CharField(blank=True, max_length=50, null=True)),
                ('serves', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
